export const themes = {
    light: {
      '--background-color': '#fff',
      '--text-color': '#333',
      '--hand-color': '#666',
      '--button-color': '#333',
      '--button-background-color': '#fff',
      '--hour-marker-color': '#333',
      '--horloge-background-color': '#fff',
      '--horloge-border-color': '#333',
      '--hand-color-hour': '#333',
      '--hand-color-minute': '#666',
      '--hand-color-second': '#999',
      '--number-color': '#333',
      '--horloge-border-radius': '50%',
      '--horloge-background': '#fff',
      '--p-text-color': '#333', 
      '--h1-text-color': '#333', 
    },
    dark: {
      '--background-color': '#1f4037',
      '--text-color': '#fff',
      '--hand-color': '#ccc',
      '--button-color': '#fff',
      '--button-background-color': '#333',
      '--hour-marker-color': '#fff',
      '--horloge-background-color': '#333',
      '--horloge-border-color': '#fff',
      '--hand-color-hour': '#ccc',
      '--hand-color-minute': '#aaa',
      '--hand-color-second': '#bbb',
      '--number-color': '#fff',
      '--horloge-border-radius': '50%',
      '--horloge-background': '#333',
      '--h1-text-color': '#fff',
      '--p-text-color': '#ddd', 
    },
  };